//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NäyttöProjekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurssivalinnat
    {
        public int KurssivalinnatID { get; set; }
        public int OpiskelijaID { get; set; }
        public int KurssiID { get; set; }
    
        public virtual Kurssit Kurssit { get; set; }
        public virtual Opiskelija Opiskelija { get; set; }
    }
}
