//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NäyttöProjekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurssit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurssit()
        {
            this.Kurssivalinnat = new HashSet<Kurssivalinnat>();
        }
    
        public int KurssiID { get; set; }
        public string Nimi { get; set; }
        public string Kuvaus { get; set; }
        public Nullable<System.DateTime> alkuPvm { get; set; }
        public Nullable<System.DateTime> loppuPvm { get; set; }
        public string Laajuus { get; set; }
        public string Toteutuskausi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurssivalinnat> Kurssivalinnat { get; set; }
    }
}
