//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NäyttöProjekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiskelija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opiskelija()
        {
            this.Kurssivalinnat = new HashSet<Kurssivalinnat>();
        }
    
        public int OpiskelijaID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Puhelin { get; set; }
        public string Email { get; set; }
        public string Osoite { get; set; }
        public Nullable<int> PostinumeroID { get; set; }
        public string Lisatiedot { get; set; }
    
        public virtual Postitoimipaikat Postitoimipaikat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurssivalinnat> Kurssivalinnat { get; set; }
    }
}
