//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NäyttöProjekti.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpiskelijaTietokantaEntities : DbContext
    {
        public OpiskelijaTietokantaEntities()
            : base("name=OpiskelijaTietokantaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Opiskelija> Opiskelija { get; set; }
        public virtual DbSet<Postitoimipaikat> Postitoimipaikat { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Kurssit> Kurssit { get; set; }
        public virtual DbSet<Kurssivalinnat> Kurssivalinnat { get; set; }
    }
}
